# Edge OS — Calamares Services Module
#
# Enables systemd services on the installed system.

---
services:
    -   name: "sddm"
        mandatory: true
    -   name: "NetworkManager"
        mandatory: true
