#!/usr/bin/env bash
# Edge OS — GRUB Btrfs Snapshot Boot Integration
#
# Generates GRUB custom menu entries (40_custom) for booting into
# Btrfs snapshots. Compatible with snapper snapshots and raw btrfs snapshots.
#
# Uses snapper's rollback snapshot convention:
#   /.snapshots/<number>/snapshot  (snapper-format snapshots)
# Also supports raw @-snapshot btrfs subvolumes.
#
# Usage:
#   sudo ./system/btrfs/grub-update.sh install   # Install snapshot boot entries
#   sudo ./system/btrfs/grub-update.sh remove    # Remove snapshot boot entries
#   sudo ./system/btrfs/grub-update.sh update    # Regenerate entries + update-grub
#   sudo ./system/btrfs/grub-update.sh status    # Show snapshot and boot status

set -Eeuo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

GRUB_CUSTOM="/etc/grub.d/41_edge_snapshots"
GRUB_MAIN_CONFIG="/boot/grub/grub.cfg"
SNAPSHOTS_DIR="/.snapshots"
MAX_SNAPSHOT_ENTRIES=10

# ─── Help ───
usage() {
    cat <<EOF
Usage: $(basename "$0") <command>

Commands:
  install  Install snapshot boot entries into GRUB
  remove   Remove snapshot boot entries from GRUB
  update   Regenerate entries and run update-grub
  status   Show snapshot and GRUB status

The script generates GRUB menu entries for booting from Btrfs snapshots,
allowing easy rollback directly from the boot menu.
EOF
    exit 0
}

# ─── Pre-flight ───
check_prereqs() {
    if [ "$(id -u)" -ne 0 ]; then
        echo -e "${RED}❌ This command must be run as root.${NC}" >&2
        exit 1
    fi

    if ! command -v grub-mkconfig &>/dev/null && ! command -v update-grub &>/dev/null; then
        echo -e "${RED}❌ GRUB tools not found. Install grub2-common.${NC}" >&2
        exit 1
    fi
}

# ─── Detect kernel and initramfs files ───
detect_kernel_initrd() {
    local kernel=""
    local initrd=""

    # Find the latest kernel in /boot
    # shellcheck disable=SC2012 # ls -t needed for sorting by modification time
    kernel=$(ls -t /boot/vmlinuz-* 2>/dev/null | head -1 || true)
    # shellcheck disable=SC2012 # ls -t needed for sorting by modification time
    initrd=$(ls -t /boot/initrd.img-* 2>/dev/null | head -1 || true)

    # Fallback to standard names
    [ -z "$kernel" ] && kernel="/boot/vmlinuz-edge"
    [ -z "$initrd" ] && initrd="/boot/initramfs-edge.cpio.xz"

    # Use plain basenames (GRUB sees /boot/ on its root device)
    echo "$(basename "$kernel") $(basename "$initrd")"
}

# ─── Find snapshots ───
find_snapper_snapshots() {
    if ! command -v snapper &>/dev/null; then
        return
    fi

    # Find snapper configs
    for config in /etc/snapper/configs/*; do
        [ -f "$config" ] || continue
        local config_name
        config_name=$(basename "$config")

        # snapper list — extract number and description
        snapper -c "$config_name" list --columns number,description 2>/dev/null | \
            tail -n +2 | while read -r num desc; do
            [ -n "$num" ] && [ "$num" -gt 0 ] 2>/dev/null || continue
            [ -z "$desc" ] && desc="snapshot-${num}"
            echo "snapper|${config_name}|${num}|${desc}"
        done
    done
}

find_raw_snapshots() {
    if [ ! -d "$SNAPSHOTS_DIR" ]; then
        return
    fi

    # Raw btrfs snapshots named @-*
    for snap in "$SNAPSHOTS_DIR"/@-*; do
        [ -d "$snap" ] || continue
        local name
        name=$(basename "$snap")
        local desc="${name#@-}"
        echo "raw|root|${name}|${desc}"
    done
}

# ─── Generate GRUB custom config ───
generate_entries() {
    read -r kernel initrd <<< "$(detect_kernel_initrd)"

    if [ -z "$kernel" ]; then
        echo -e "${RED}❌ No kernel found in /boot${NC}" >&2
        exit 1
    fi

    # Collect snapshots
    local -a entries=()

    while IFS='|' read -r type config num desc; do
        [ -z "$type" ] && continue
        entries+=("${type}|${config}|${num}|${desc}")
    done < <(find_snapper_snapshots; find_raw_snapshots)

    # Get kernel cmdline from current /proc/cmdline
    local cmdline="rootflags=subvol=/@ rw quiet splash loglevel=3"

    # Get root device
    local root_dev
    root_dev=$(findmnt -n -o SOURCE / | sed 's/\[.*\]//' | xargs -I{} readlink -f {} 2>/dev/null || echo "/dev/sda2")

    # Generate config
    cat > "$GRUB_CUSTOM" << 'GRUB_HEADER'
#!/bin/sh
# Edge OS — Btrfs Snapshot Boot Entries
# Generated by system/btrfs/grub-update.sh
# DO NOT EDIT MANUALLY — run grub-update.sh to regenerate
#
# This file adds boot entries for Btrfs snapshots
# allowing rollback directly from the GRUB menu.

GRUB_HEADER

    {
        echo ""
        echo "### BEGIN: Edge OS Btrfs Snapshots ###"
        echo ""

        if [ ${#entries[@]} -eq 0 ]; then
            echo "# No snapshots found"
        fi

        # Normal boot entry (current default)
        echo "menuentry 'Edge OS — Current System' --id edge-current {"
        echo "  linux /${kernel} root=UUID=$(blkid -s UUID -o value "$root_dev" 2>/dev/null || echo "") ${cmdline}"
        echo "  initrd /${initrd}"
        echo "}"

        # Recovery mode
        echo ""
        echo "menuentry 'Edge OS — Recovery Mode' --id edge-recovery {"
        echo "  linux /${kernel} root=UUID=$(blkid -s UUID -o value "$root_dev" 2>/dev/null || echo "") ${cmdline} single"
        echo "  initrd /${initrd}"
        echo "}"

        # Snapshot entries (up to MAX_SNAPSHOT_ENTRIES)
        local count=0
        for entry in "${entries[@]}"; do
            [ "$count" -ge "$MAX_SNAPSHOT_ENTRIES" ] && break
            IFS='|' read -r type config num desc <<< "$entry"

            local safe_desc
            safe_desc="$(echo "$desc" | sed 's/[\/"]/\\&/g')"

            echo ""
            if [ "$type" = "snapper" ]; then
                local snap_path="/.snapshots/${num}/snapshot"
                echo "menuentry '📸 Edge OS — Snapshot #${num}: ${safe_desc}' --id edge-snapshot-${num} {"
                echo "  linux /${kernel} root=UUID=$(blkid -s UUID -o value "$root_dev" 2>/dev/null || echo "") rootflags=subvol=/.snapshots/${num}/snapshot ${cmdline}"
                echo "  initrd /${initrd}"
                echo "}"
            elif [ "$type" = "raw" ]; then
                local snap_subvol="${num}"
                echo "menuentry '📸 Edge OS — Snapshot: ${safe_desc}' --id edge-snapshot-${snap_subvol} {"
                echo "  linux /${kernel} root=UUID=$(blkid -s UUID -o value "$root_dev" 2>/dev/null || echo "") rootflags=subvol=${snap_subvol} ${cmdline}"
                echo "  initrd /${initrd}"
                echo "}"
            fi

            count=$((count + 1))
        done

        echo ""
        echo "### END: Edge OS Btrfs Snapshots ###"
    } >> "$GRUB_CUSTOM"

    chmod 755 "$GRUB_CUSTOM"
    echo -e "${GREEN}  ✅ Generated ${GRUB_CUSTOM}${NC}"
    echo -e "${GREEN}     Found ${#entries[@]} snapshots, showing ${count} entries${NC}"
}

# ─── Command: install ───
cmd_install() {
    echo -e "${GREEN}🔧 Installing Btrfs snapshot GRUB entries...${NC}"
    generate_entries

    echo -e "${GREEN}🔄 Running update-grub...${NC}"
    if command -v update-grub &>/dev/null; then
        update-grub
    else
        grub-mkconfig -o "$GRUB_MAIN_CONFIG"
    fi

    echo -e "${GREEN}✅ Snapshot boot entries installed.${NC}"
    echo "   Snapshot entries appear in the GRUB menu under '📸' headings."
}

# ─── Command: remove ───
cmd_remove() {
    echo -e "${YELLOW}🗑️  Removing Btrfs snapshot GRUB entries...${NC}"

    if [ -f "$GRUB_CUSTOM" ]; then
        rm "$GRUB_CUSTOM"
        echo -e "${GREEN}  ✅ Removed ${GRUB_CUSTOM}${NC}"
    else
        echo -e "${YELLOW}  ⚠ No snapshot GRUB config found${NC}"
    fi

    if command -v update-grub &>/dev/null; then
        update-grub
    else
        grub-mkconfig -o "$GRUB_MAIN_CONFIG"
    fi

    echo -e "${GREEN}✅ Snapshot boot entries removed.${NC}"
}

# ─── Command: update ───
cmd_update() {
    echo -e "${GREEN}🔄 Updating Btrfs snapshot GRUB entries...${NC}"

    if [ -f "$GRUB_CUSTOM" ]; then
        rm "$GRUB_CUSTOM"
    fi

    generate_entries

    if command -v update-grub &>/dev/null; then
        update-grub
    else
        grub-mkconfig -o "$GRUB_MAIN_CONFIG"
    fi

    echo -e "${GREEN}✅ GRUB snapshot entries updated.${NC}"
}

# ─── Command: status ───
cmd_status() {
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${CYAN}  GRUB Btrfs Snapshot Status${NC}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

    # GRUB custom config
    echo -e "\n${GREEN}GRUB Custom Config:${NC}"
    if [ -f "$GRUB_CUSTOM" ]; then
        local entry_count
        entry_count=$(grep -c 'menuentry' "$GRUB_CUSTOM" || true)
        echo "  File: ${GRUB_CUSTOM}"
        echo "  Entries: ${entry_count}"
    else
        echo -e "  ${YELLOW}Not installed${NC}"
    fi

    # Snapper status
    echo -e "\n${GREEN}Snapper Configs:${NC}"
    if command -v snapper &>/dev/null; then
        for config in /etc/snapper/configs/*; do
            [ -f "$config" ] || continue
            local name
            name=$(basename "$config")
            local count
            count=$(snapper -c "$name" list 2>/dev/null | tail -n +3 | wc -l)
            echo "  ${name}: ${count} snapshots"
        done
    else
        echo -e "  ${YELLOW}snapper not installed${NC}"
    fi

    # Root device
    echo -e "\n${GREEN}Root Device:${NC}"
    findmnt / -o SOURCE,FSTYPE,OPTIONS 2>/dev/null | tail -1

    # Bootloader
    echo -e "\n${GREEN}Bootloader:${NC}"
    if [ -d /boot/grub ]; then
        echo "  GRUB: installed"
        if [ -f "$GRUB_MAIN_CONFIG" ]; then
            echo "  Config: ${GRUB_MAIN_CONFIG} ($(wc -l < "$GRUB_MAIN_CONFIG") lines)"
        fi
    else
        echo "  ${YELLOW}GRUB not found (are you running in a chroot?)${NC}"
    fi
}

# ─── Main ───
check_prereqs

COMMAND="${1:-help}"

case "$COMMAND" in
    install)
        cmd_install
        ;;
    remove)
        cmd_remove
        ;;
    update)
        cmd_update
        ;;
    status)
        cmd_status
        ;;
    help|--help|-h)
        usage
        ;;
    *)
        echo -e "${RED}❌ Unknown command: ${COMMAND}${NC}" >&2
        usage
        ;;
esac
