#!/usr/bin/env bash
# Edge OS — Calamares Btrfs Subvolume Layout Creator
#
# Creates the standard Edge OS Btrfs subvolume layout after the
# partition module has formatted the root partition as Btrfs.
#
# Environment variables set by Calamares:
#   ROOTFS_DIR — the mount point where the root filesystem is mounted
#
# This script creates subvolumes on the formatted Btrfs partition
# and remounts them at the correct mount points for unpackfs.

set -Eeuo pipefail

ROOTFS_DIR="${ROOTFS_DIR:-/mnt/edge}"
BTRFS_DEVICE=""
TOP_MNT=""

# Cleanup on error
cleanup() {
    if [ -n "$TOP_MNT" ] && mountpoint -q "$TOP_MNT" 2>/dev/null; then
        umount "$TOP_MNT" 2>/dev/null || true
        rmdir "$TOP_MNT" 2>/dev/null || true
    fi
}
trap cleanup EXIT

echo "[edge-btrfs] Creating Btrfs subvolume layout..."

# ─── Find the Btrfs mount point ───
# Check common locations where Calamares mounts the target
for candidate in "$ROOTFS_DIR" /mnt /tmp/calamares-root-* /tmp/calamares-*; do
    if [ -d "$candidate" ] && mountpoint -q "$candidate" 2>/dev/null; then
        FSTYPE=$(findmnt -n -o FSTYPE "$candidate" 2>/dev/null || echo "")
        if [ "$FSTYPE" = "btrfs" ] || [ -z "$FSTYPE" ]; then
            ROOTFS_DIR="$candidate"
            break
        fi
    fi
done
unset candidate

# Find the Btrfs device
BTRFS_DEVICE=$(findmnt -n -o SOURCE "$ROOTFS_DIR" 2>/dev/null | sed 's/\[.*\]//' || true)

if [ -z "$BTRFS_DEVICE" ]; then
    # Try to find any Btrfs device that has been formatted but not mounted
    BTRFS_DEVICE=$(blkid | grep 'TYPE="btrfs"' | head -1 | cut -d: -f1)
fi

if [ -z "$BTRFS_DEVICE" ]; then
    echo "[edge-btrfs] ⚠ No Btrfs device found at ${ROOTFS_DIR}"
    echo "[edge-btrfs]    Skipping subvolume creation (filesystem may not be Btrfs)"
    exit 0
fi

echo "[edge-btrfs] Device: ${BTRFS_DEVICE}"
echo "[edge-btrfs] Mount: ${ROOTFS_DIR}"

# ─── Check if we're on Btrfs ───
FSTYPE=$(findmnt -n -o FSTYPE "$ROOTFS_DIR" 2>/dev/null || echo "")
if [ "$FSTYPE" != "btrfs" ]; then
    echo "[edge-btrfs] ⚠ Not a Btrfs filesystem (${FSTYPE}), skipping subvolume creation"
    exit 0
fi

# ─── Define subvolumes ───
declare -a SUBVOLUMES=(
    "@"
    "@home"
    "@snapshots"
    "@swap"
    "@cache"
    "@log"
)

# ─── Create subvolumes at top-level ───
echo "[edge-btrfs] Creating subvolumes on ${BTRFS_DEVICE}..."

# Remount at top-level (subvolid=5) to create subvolumes
TOP_MNT=$(mktemp -d)
mount -t btrfs -o subvolid=5 "$BTRFS_DEVICE" "$TOP_MNT"

for sv in "${SUBVOLUMES[@]}"; do
    if [ -d "$TOP_MNT/$sv" ]; then
        echo "[edge-btrfs] ⚠ Subvolume ${sv} already exists, skipping"
    else
        btrfs subvolume create "$TOP_MNT/$sv"
        echo "[edge-btrfs] ✅ Created ${sv}"
    fi
done

# Set @ as default subvolume
ROOT_ID=$(btrfs subvolume list "$TOP_MNT" | grep ' @$' | awk '{print $2}')
if [ -n "$ROOT_ID" ]; then
    btrfs subvolume set-default "$ROOT_ID" "$TOP_MNT"
    echo "[edge-btrfs] ✅ Set @ (ID ${ROOT_ID}) as default subvolume"
fi

# ─── Remount @ as root ───
umount "$ROOTFS_DIR" 2>/dev/null || true
mount -t btrfs -o subvol=@,compress=zstd:3,noatime,ssd "$BTRFS_DEVICE" "$ROOTFS_DIR"

# Create sub-directory mount points inside @
for dir in home .snapshots .swap var/cache var/log; do
    mkdir -p "$ROOTFS_DIR/$dir"
done

# Mount subvolumes
mount -t btrfs -o subvol=@home,compress=zstd:3,noatime,ssd "$BTRFS_DEVICE" "$ROOTFS_DIR/home"
mount -t btrfs -o subvol=@snapshots,noatime,ssd "$BTRFS_DEVICE" "$ROOTFS_DIR/.snapshots"
mount -t btrfs -o subvol=@swap,noatime,ssd,nodatacow "$BTRFS_DEVICE" "$ROOTFS_DIR/.swap"
mount -t btrfs -o subvol=@cache,compress=zstd:3,noatime,ssd,nodatacow "$BTRFS_DEVICE" "$ROOTFS_DIR/var/cache"
mount -t btrfs -o subvol=@log,compress=zstd:1,noatime,ssd,nodatacow "$BTRFS_DEVICE" "$ROOTFS_DIR/var/log"

# Add to fstab
UUID=$(blkid -s UUID -o value "$BTRFS_DEVICE")
FSTAB_FILE="$ROOTFS_DIR/etc/fstab"
mkdir -p "$(dirname "$FSTAB_FILE")"

cat > "$FSTAB_FILE" <<FSTAB
# /etc/fstab — Edge OS Btrfs subvolume mounts
# Generated by Calamares installer

UUID=${UUID}  /  btrfs  compress=zstd:3,noatime,ssd  0  0
UUID=${UUID}  /home  btrfs  subvol=@home,compress=zstd:3,noatime,ssd  0  0
UUID=${UUID}  /.snapshots  btrfs  subvol=@snapshots,noatime,ssd  0  0
UUID=${UUID}  /.swap  btrfs  subvol=@swap,noatime,ssd,nodatacow  0  0
UUID=${UUID}  /var/cache  btrfs  subvol=@cache,compress=zstd:3,noatime,ssd,nodatacow  0  0
UUID=${UUID}  /var/log  btrfs  subvol=@log,compress=zstd:1,noatime,ssd,nodatacow  0  0
FSTAB

echo "[edge-btrfs] ✅ fstab generated"

# Clean up top-level mount
umount "$TOP_MNT" 2>/dev/null || true
rmdir "$TOP_MNT" 2>/dev/null || true

echo "[edge-btrfs] ✅ Btrfs subvolume layout complete"
